spring.application.name=AutaZa

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

spring.datasource.url=jdbc:postgresql://dpg-d4ft7em3jp1c73d8thcg-a:5432/autaza_api_sql
spring.datasource.username=autaza_api_sql_user
spring.datasource.password=mKUhYQykV7Js6FGi82e1M8hguLtSzXkE
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.data-source-properties.sslmode=require

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.leak-detection-threshold=60000

server.address=0.0.0.0
server.port=${PORT:8080}



#Falta configurar la base de datos xd
